layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: 
      - RealBrandonChen
      - Algorothms-In-Java-Way
      - AWS-LambdaFunction-Examples
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: brandon-peng-chen-80a750173
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: /resume/
  # youtube: your_username

topics:
  - name: Unity
    web_url: https://unity.com/
    image_url: https://unity3d.com/profiles/unity3d/themes/unity/images/pages/branding_trademarks/unity-tab-square-black.png

  - name: TensorFlow
    web_url: https://www.tensorflow.org/
    image_url: https://www.logolynx.com/images/logolynx/ff/fffb2a56e7e2cbd994adb1eda8f3d8c2.jpeg

  - name: Django
    web_url: https://www.djangoproject.com/
    image_url: https://seeklogo.com/images/D/django-logo-4C5ECF7036-seeklogo.com.png
